= CORS-less Node

Run reverse proxy to avoid CORS error while calling Casper nodes from browser.

*Note:* This is limitation that should be fixed in node 1.5.0.

== Requirements

* which
* docker
* curl
* jq

== Usage

If you want to proxy specific node:

[source,bash]
----
$ ./run.sh 135.181.216.142 7777
----

Alternatively, you can get node picked randomly among `mainnet` and `testnet`:

[source,bash]
----
$ ./run.sh testnet
----

After successful launch, proxy container will be running in background (with auto restart), but it might be stopped and removed:

[source,bash]
----
$ docker stop corsless-casper-node
$ docker rm corsless-casper-node
----

=== HTTPS support

There is option to enable HTTPS in this proxy, by simply placing PEM file under `./mitmproxy/cert.pem`. It should be in the following format: 

[source]
----
-----BEGIN PRIVATE KEY-----
<private key>
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
<cert>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<intermediary cert (optional)>
-----END CERTIFICATE-----
----

It will be picked automatically during proxy startup.

[TIP]
====
You can use **Let's Encrypt** to get free certificates for your domain!

After getting them, simply combine files to obtain valid `cert.pem`:

[source, bash]
----
cat /etc/letsencrypt/live/casper-node.xyz/privkey.pem /etc/letsencrypt/live/casper-node.xyz/fullchain.pem > ./mitmproxy/cert.pem
----
====

== Notes

You can get list of connected peers from any node. You can also visit https://casper.onrender.com/[this helper tool].
